// Generated by Apple Swift version 3.1 (swiftlang-802.0.51 clang-802.0.41)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if defined(__has_attribute) && __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if defined(__has_attribute) && __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import Foundation;
@import UIKit;
@import ObjectiveC;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
typedef SWIFT_ENUM(NSInteger, AdType) {
  AdTypeAdTypeNone = 0,
  AdTypeAdTypeCardAd = 1,
  AdTypeAdTypeRewardedVideo = 2,
  AdTypeAdTypeInterstitialVideo = 3,
};


@interface NSRecursiveLock (SWIFT_EXTENSION(YouAppi))
@end


@interface UILabel (SWIFT_EXTENSION(YouAppi))
@end


@interface UIView (SWIFT_EXTENSION(YouAppi))
@end


@interface NSURLSessionTask (SWIFT_EXTENSION(YouAppi))
@end


SWIFT_CLASS("_TtC7YouAppi4YAAd")
@interface YAAd : NSObject
@property (nonatomic, weak) id _Nullable delegate;
- (BOOL)isAvailable SWIFT_WARN_UNUSED_RESULT;
- (void)show;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7YouAppi8YAAdCard")
@interface YAAdCard : YAAd
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@property (nonatomic, weak) id _Nullable delegate;
- (void)show;
- (BOOL)isAvailable SWIFT_WARN_UNUSED_RESULT;
@end

@class YouAppi;

SWIFT_PROTOCOL("_TtP7YouAppi12YAAdDelegate_")
@protocol YAAdDelegate
@optional
- (void)adDidInitializeWithYouAppi:(YouAppi * _Nonnull)youAppi adType:(enum AdType)adType;
- (void)adRetrievalFailedWithYouAppi:(YouAppi * _Nonnull)youAppi adType:(enum AdType)adType error:(NSError * _Nonnull)error;
- (void)adPreloadFailedWithYouAppi:(YouAppi * _Nonnull)youAppi adType:(enum AdType)adType error:(NSError * _Nonnull)error;
- (void)adDidChangeAvailabilityWithYouAppi:(YouAppi * _Nonnull)youAppi adType:(enum AdType)adType isAvailable:(BOOL)isAvailable;
- (void)adDidShownWithYouAppi:(YouAppi * _Nonnull)youAppi adType:(enum AdType)adType;
- (void)adDidCloseWithYouAppi:(YouAppi * _Nonnull)youAppi adType:(enum AdType)adType;
- (void)adDidStartedWithYouAppi:(YouAppi * _Nonnull)youAppi adType:(enum AdType)adType;
- (void)adDidEndWithYouAppi:(YouAppi * _Nonnull)youAppi adType:(enum AdType)adType;
- (void)adDidRewardedWithYouAppi:(YouAppi * _Nonnull)youAppi adType:(enum AdType)adType;
- (void)adWillLeaveApplicationWithYouAppi:(YouAppi * _Nonnull)youAppi adType:(enum AdType)adType;
@end


SWIFT_CLASS("_TtC7YouAppi21YAAdInterstitialVideo")
@interface YAAdInterstitialVideo : YAAd
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@property (nonatomic, weak) id _Nullable delegate;
- (void)show;
- (BOOL)isAvailable SWIFT_WARN_UNUSED_RESULT;
@end

@protocol YALoggerDelegate;

SWIFT_CLASS("_TtC7YouAppi10YAAdLogger")
@interface YAAdLogger : NSObject
@property (nonatomic, weak) id <YALoggerDelegate> _Nullable delegate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7YouAppi17YAAdRewardedVideo")
@interface YAAdRewardedVideo : YAAd
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
@property (nonatomic, weak) id _Nullable delegate;
- (void)show;
- (BOOL)isAvailable SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, YALogLevel) {
  YALogLevelNone = 1,
  YALogLevelAll = 2,
  YALogLevelDebug = 3,
  YALogLevelInfo = 4,
  YALogLevelWarning = 5,
  YALogLevelError = 6,
  YALogLevelAssert = 7,
};

typedef SWIFT_ENUM(NSInteger, YALogTag) {
  YALogTagApi = 0,
  YALogTagCallback = 1,
  YALogTagSdk = 2,
};


SWIFT_PROTOCOL("_TtP7YouAppi16YALoggerDelegate_")
@protocol YALoggerDelegate
@optional
- (void)logDidReceivedInformationWithYouAppi:(YouAppi * _Nonnull)youAppi tag:(enum YALogTag)tag logLevel:(enum YALogLevel)logLevel message:(NSString * _Nonnull)message error:(NSError * _Nullable)error;
@end


SWIFT_CLASS("_TtC7YouAppi7YouAppi")
@interface YouAppi : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) YouAppi * _Nonnull sharedInstance;)
+ (YouAppi * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull environment;
@property (nonatomic, copy) NSString * _Null_unspecified accessToken;
@property (nonatomic) BOOL isInitialized;
- (void)initializeWithAccessToken:(NSString * _Null_unspecified)accessToken;
- (YAAdCard * _Nullable)cardAd SWIFT_WARN_UNUSED_RESULT;
- (YAAdRewardedVideo * _Nullable)rewardedVideo SWIFT_WARN_UNUSED_RESULT;
- (YAAdInterstitialVideo * _Nullable)interstitialVideo SWIFT_WARN_UNUSED_RESULT;
- (YAAdLogger * _Nullable)log SWIFT_WARN_UNUSED_RESULT;
- (void)logLevel:(enum YALogLevel)logLevel;
- (NSString * _Nonnull)version SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
